flask_edits/__init__.py
"""Flask-Edits
"""

from flask import request
from jinja2.environment import copy_cache

from collections import OrderedDict
import json
import os

from .editable import EditableExtension
from .views import edits


class Edits(object):
    def __init__(self, app=None):
        self.app = app

        if app is not None:
            self.init_app(app)

    def init_app(self, app):
        """
            Register the Jinja extension, load edits from 
            app.config['EDITS_PATH'] and register blueprints.

            :param app:
                Flask application instance
        """
        app.config.setdefault('EDITS_URL', '/edits')
        app.config.setdefault('EDITS_PREVIEW', True)
        app.config.setdefault('EDITS_SUMMERNOTE', False)

        if 'EDITS_PATH' not in app.config:
            raise Exception('EDITS_PATH not set in app configuration.')

        if os.path.isfile(app.config['EDITS_PATH']):
            with open(app.config['EDITS_PATH']) as f:
                _db = json.loads(f.read(), object_pairs_hook=OrderedDict)
        else:
            _db = OrderedDict()

        app.jinja_env.add_extension('flask.ext.edits.EditableExtension')
        app.jinja_env.edits = _db
        app.jinja_env.edits_preview = app.config['EDITS_PREVIEW']
        app.jinja_env.edits_cache = copy_cache(app.jinja_env.cache)

        if app.config['EDITS_PREVIEW']:
            app.jinja_env.cache = None

        app.register_blueprint(edits, url_prefix=app.config['EDITS_URL'])

flask_edits/views.py
"""Edits Admin Blueprint
"""

import os
import json

import jinja2
from jinja2.environment import copy_cache

from flask import (
    Blueprint,
    current_app,
    render_template,
    request,
    redirect,
    url_for,
)

edits = Blueprint('edits', __name__, template_folder='templates', static_folder='static')

@edits.route('/', defaults={'page': None})
@edits.route('/<path:page>')
def index(page):
    _db = current_app.jinja_env.edits

    if _db:
        if not page:
            page = _db.iterkeys().next()
    else:
        page = None

    return render_template('edits-admin.j2',
                           edits=_db,
                           page=page,
                           summernote=current_app.config['EDITS_SUMMERNOTE'],
                           preview=current_app.jinja_env.edits_preview)

@edits.route('/preview', methods=['POST'])
def preview():
    if request.form.get('state') == 'true':
        preview = True
        cache = None
    else:
        preview = False
        cache = copy_cache(current_app.jinja_env.edits_cache)

    current_app.jinja_env.edits_preview = preview
    current_app.jinja_env.cache = cache

    if current_app.jinja_env.cache:
        current_app.jinja_env.cache.clear()

    return ''

@edits.route('/save', methods=['POST'])
def save():
    _db = current_app.jinja_env.edits

    page = request.form.get('page')

    for field in request.form:
        if field != 'page':
            value = request.form.get(field)

            if value == '':
                value = None

            _db[page][field]['edited'] = value

    if current_app.jinja_env.cache:
        current_app.jinja_env.cache.clear()

    with open(current_app.config['EDITS_PATH'], 'w') as f:
        f.write(json.dumps(_db, indent=4))

    return redirect(url_for('edits.index', page=page))

flask_edits/templates/edits-admin.j2
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Flask-Edits</title>

    <link href="{{ url_for('edits.static', filename='bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" />
    <link href="{{ url_for('edits.static', filename='bootstrap/css/navbar.css')}}" rel="stylesheet" />
    <link href="{{ url_for('edits.static', filename='bootstrap-switch/css/bootstrap-switch.min.css') }}" rel="stylesheet">

    {% if summernote %}
    <link href="{{ url_for('edits.static', filename='summernote/summernote.css') }}" rel="stylesheet" />
    <link href="{{ url_for('edits.static', filename='summernote/summernote-bs3.css') }}" rel="stylesheet" />
    <link href="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.min.css" rel="stylesheet" />
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet" />
    {% endif %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="container">
      <div class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">Flask-Edits</a>
          </div>
          <div class="pull-right" style="margin-top: 10px;">
              <label style="font-weight: normal; vertical-align: bottom">Preview</label>
              &nbsp;&nbsp;
              <input type="checkbox" name="mode" {% if preview %}checked{% endif %} />
            </div>
        </div>
      </div>

      {% if edits|length %}
      <div class="row">
        <div class="col-sm-4">
          <div class="panel panel-default">
            <div class="panel-heading">Editable Pages</div>
            <div class="list-group">
              {% for page, regions in edits.iteritems() %}
              <a href="{{ url_for('edits.index', page=page) }}" class="list-group-item">
                <span class="badge">{{ regions.keys()|length }}</span>
                {{ page }}
              </a>
              {% endfor %}
            </div>
          </div>
        </div>

        <div class="col-sm-8">
            <p class="lead">Editing {{ page }}</p>
            <form method="POST" action="{{ url_for('edits.save') }}" onsubmit="save()">
                <input type="hidden" name="page" value="{{ page }}" />
                {% for key, section in edits[page].iteritems() %}
                  <small><strong>{{ key|upper }}</strong></small>
                  <div class="form-group" style="margin-top: 5px;">
                    {% if summernote %}
                      <div class="summernote" id="{{ key }}">{% if section.edited is none %}{{ section.original }}{% else %}{{ section.edited }}{% endif %}</div>
                      <input type="hidden" name="{{ key }}" value="" />
                    {% else %}
                      <textarea class="form-control" rows="4" name="{{ key }}">{% if section.edited is none %}{{ section.original }}{% else %}{{ section.edited }}{% endif %}</textarea>
                    {% endif %}
                  </div>
                {% endfor %}
                <input type="submit" value="Save Page" class="btn btn-primary" />
            </form>
        </div>
      </div>
      {% else %}
      <div class="row">
        <div class="col-sm-12" style="text-align: center; padding-top: 40px;">
          <i class="glyphicon glyphicon-warning-sign" style="font-size: 100px; color: #eee;"></i>
          <p class="lead" style="width: 50%; margin: 0 auto; padding-top: 40px;">No editable pages loaded yet. After adding editable regions to your templates, visit each page in your browser to load it.</p>
        </div>
      </div>
      {% endif %}
    </div>
  </body>

  <script type="text/javascript" src="//code.jquery.com/jquery-1.9.1.min.js"></script> 
  <script type="text/javascript" src="{{ url_for('edits.static', filename='bootstrap-switch/js/bootstrap-switch.min.js') }}"></script>

  {% if summernote %}
  <script type="text/javascript" src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script> 
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.min.js"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/mode/xml/xml.min.js"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/2.36.0/formatting.min.js"></script>
  <script type="text/javascript" src="{{ url_for('edits.static', filename='summernote/summernote.min.js') }}"></script>
  {% endif %}

  <script>
    $(document).ready(function() {
      $('[name="mode"]').bootstrapSwitch({
        onText: 'On',
        offText: 'Off',
        onSwitchChange: function(e, state) {
          $.post("{{ url_for('edits.preview') }}", {state: state});
        }
      });

      {% if summernote %}
      $('.summernote').summernote({
        height: 100,
        toolbar: [
          ['style', ['bold', 'italic', 'underline', 'clear']],
          ['insert', ['link', 'hr']],
          ['layount', ['ul', 'ol']],
          ['misc', ['codeview']]
        ]
      });
      {% endif %}
    });

    {% if summernote %}
    function save() {
      $('.summernote').each(function() {
        $('input[name=' + $(this).attr('id') + ']').val($(this).code());
      });
    }
    {% endif %}
  </script>
</html>